// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatRefreshController from "./chat_refresh_controller"
application.register("chat_refresh", ChatRefreshController)

import RoomRefreshController from "./room_refresh_controller"
application.register("room_refresh", RoomRefreshController)
